# Generated by Django 2.0.2 on 2018-03-03 11:35

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_auto_20180302_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(max_length=32)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('type', models.CharField(max_length=32)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.Person')),
            ],
        ),
    ]
