# Generated by Django 2.0.2 on 2018-03-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_num',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_num',
            field=models.CharField(max_length=32),
        ),
    ]
