# Generated by Django 2.0.2 on 2018-03-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_auto_20180304_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_num',
            field=models.IntegerField(),
        ),
    ]
